name: Deploy to NuGet.org

on:
  push:
    branches:
      - mainline
    tags:
      - 'release/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and pack
        run: |
          dotnet pack --configuration Release

      - name: Push package to NuGet.org
        run: |
          dotnet nuget push ./bin/Release/*.nupkg \
            -k ${{ secrets.SKYWARDNUGETAPIKEY }} \
            -s https://api.nuget.org/v3/index.json ${fileName} \
            --skip-duplicate
